baseURL = "https://shaerpour.ir"
languageCode = "en-us"
title = "AHSP"
theme="archie"
copyright = "Â© 2025 Amirhossein Shaerpour"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
[params]
	mode="dark"
	useCDN=false
	subtitle = "Amirhossein Shaerpour"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/shaerpour"

[[params.social]]
name = "Linkedin"
icon = "linkedin"
url = "https://linkedin.com/in/shaerpour"

[[params.social]]
name = "GitLab"
icon = "gitlab"
url = "https://gitlab.com/shaerpour"

[[menu.main]]
name = "HOME"
url = "/"
weight = 1

[[menu.main]]
name = "POSTS"
url = "/posts"
weight = 2

[[menu.main]]
name = "ABOUT"
url = "/about"
weight = 3

[[menu.main]]
name = "SHELF"
url = "/SHELF"
weight = 4
